### ISSUE TITLE
UT case fail because of cpu's nll_loss2d backward

### ISSUE THREAD

**Issue by chunhuanMeng** [intel/torch-xpu-ops#227]
### 🚀 The feature, motivation and pitch

Ut case <test_comprehensive_nn_functional_nll_loss_xpu_float16> fail because of cpu's nll_loss2d backward.We should try this ut when we implement xpu nll_loss2d op.

**Comment by fengyuan14** [comment]
@huaiyuzh Please update your latest findings.

**Comment by huaiyuzh** [comment]
The issue is accuracy issue.   
The case test_comprehensive_nn_functional_nll_loss_xpu_float16 failed in calling nll_loss2d_backward. xpu result is: 0.04122925, cuda and cpu is: 0.04119873, atol is 1e-7. We have two findings: 1) the atol of nll_loss2d_forward is just 1e-2 as below: (torch.float16, torch.ops.aten.nll_loss2d_forward.default): 1e-2, so we think the atol of backward is too high, maybe we can enlarge the atol value of nll_loss2d_backward like nll_loss2d_forward. 2) If we use compile option O0 instead of O3, xpu and cuda can the same precision, that is 0.04119873. We know that there are some optimization bugs when the xpu compiler processes +-*/ of float16 and bfloat16, I tried to use volatile in nll_loss2d_backward kernel, but it had no effect and I still could not get the same precision as cuda. 
**failure:**
RuntimeError: Difference from float64 is larger with decomposition nll_loss2d_backward.default than original on output 0. Original max diff: 1.1224856321843946e-05, Decomp max diff: 1.9292721803156054e-05
atol = 1e-07
args = (tensor(-0.20202637, device='xpu:0', dtype=torch.float16), tensor([[[[ 4.82031250,  7.34765625],
          [-3.37109375, -1.95019531]],
         [[ 3.78320312, -2.43359375],
          [-6.07812500,  5.32812500]],
         [[ 5.48046875,  2.64257812],
          [-4.53515625,  8.69531250]]],
        [[[-5.35937500, -6.23437500],
          [ 6.59765625,  3.07812500]],
         [[ 6.54687500,  7.01171875],
          [ 1.90234375, -6.60937500]],
         [[ 2.91992188,  2.51171875],
          [ 5.06640625, -0.78613281]]]], device='xpu:0', dtype=torch.float16,
       requires_grad=True), tensor([[[1, 0],
         [1, 0]],
        [[0, 1],
         [0, 0]]], device='xpu:0'), tensor([-3.88281250,  0.12963867,  6.82031250], device='xpu:0',
       dtype=torch.float16), 1, -100, tensor(-19.03125000, device='xpu:0', dtype=torch.float16))
kwargs = {}
**output:**
atol:1e-07
orig:tensor([[[[ 0.00000000,  0.04122925],
          [ 0.00000000,  0.04122925]],
         [[-0.00137711,  0.00000000],
          [-0.00137711,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]],
        [[[ 0.04122925,  0.00000000],
          [ 0.04122925,  0.04122925]],
         [[ 0.00000000, -0.00137711],
          [ 0.00000000,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]]], device='xpu:0', dtype=torch.float16)
ref:tensor([[[[ 0.00000000,  0.04121802],
          [ 0.00000000,  0.04121802]],
         [[-0.00137618,  0.00000000],
          [-0.00137618,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]],
        [[[ 0.04121802,  0.00000000],
          [ 0.04121802,  0.04121802]],
         [[ 0.00000000, -0.00137618],
          [ 0.00000000,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]]], device='xpu:0', dtype=torch.float64)
decomp:tensor([[[[-0.00000000,  0.04119873],
          [-0.00000000,  0.04119873]],
         [[-0.00137615,  0.00000000],
          [-0.00137615,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]],
        [[[ 0.04119873, -0.00000000],
          [ 0.04119873,  0.04119873]],
         [[ 0.00000000, -0.00137615],
          [ 0.00000000,  0.00000000]],
         [[ 0.00000000,  0.00000000],
          [ 0.00000000,  0.00000000]]]], device='xpu:0', dtype=torch.float16)
FAILED

**Comment by daisyden** [comment]
According to @huaiyuzh it is not ARC specific issue. IGC optimization on data type promotion.

**Comment by daisyden** [comment]
will be tracked in #754
