### ISSUE TITLE
New masked index put cases fail on complex128 and complex64 

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#464]
### 🐛 Describe the bug

`test_fn_grad__unsafe_masked_index_xpu_complex128`
`test_fn_grad__unsafe_masked_index_xpu_float64`
`test_fn_gradgrad__unsafe_masked_index_put_accumulate_xpu_complex128`
`test_fn_gradgrad__unsafe_masked_index_put_accumulate_xpu_float64`

### Versions

Lates PyTorch main

**Comment by daisyden** [comment]
The case failed because with the same op output, the torch.autograd.grad() cannot return exactly the same result. 

_unsafe_masked_index and _unsafe_masked_index_put_accumulate are two new added ops. The former will call 
```
at::_unsafe_index(self, clamped_indices);
```
and later will call
```
at::_unsafe_index_put(self, clamped_indices, masked_value, true);
```
The backward of then will call at::_index_put_impl_(), however, cuda uses the native implementation with the logic:
![image](https://github.com/intel/torch-xpu-ops/assets/27668899/2b2b11c1-17b3-46e5-b104-1bae3354c800)

That means when accumulate=True or use deterministic algorithm the kernel should be deterministic.

**Comment by daisyden** [comment]
https://github.com/intel/torch-xpu-ops/pull/474 PR is created to align with cuda.
