### ISSUE TITLE
Case regression due to PyTorch uplift

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#549]
### 🐛 Describe the bug

New failures occur when PyTorch uplifts.
Guilty commit should be between f053be2a97e1f6f9b2252cb800edd46f720af502 and d44c30e2f90d9ebe829875324f0ac662d04833a8.

- [ ] test_compare_cpu_nn_functional_batch_norm_xpu_float16
- [ ] test_compare_cpu_std_mean_xpu_bfloat16
- [x] test_compare_cpu_sub_xpu_float16
- [ ] test_compare_cpu_var_mean_xpu_bfloat16
- [x] test_symnode_hashing
- [x] test_index_ind_dtype_xpu

### Versions

Latest PyTorch.

**Comment by daisyden** [comment]
test_index_ind_dtype_xpu can pass with 10c7f037fe3271cb3865816c216007ba403f5347 and reverted PR 
https://github.com/intel/torch-xpu-ops/commit/4db0b0cd1ca51d9cfd890be2eb3527b165782220, because checkIndexTensorTypes interface changes is reverted by
https://github.com/pytorch/pytorch/commit/fb696bf26457a60583f4c43f1a6547b16725c016. So we should also revert torch-xpu-ops 4db0b0cd1ca51d9cfd890be2eb3527b165782220, add by the 2nd parameter of checkIndexTensorTypes.

**Comment by daisyden** [comment]
Penghui and I have verified the following cases are due to pytorch commit https://github.com/pytorch/pytorch/commit/c8ab2e8b637515b6488931f5e59f23848aae9991 updated the seed of make_tensor during sample input generation. The root-causing is still WIP. 

test_compare_cpu_nn_functional_batch_norm_xpu_float16
 test_compare_cpu_std_mean_xpu_bfloat16
 test_compare_cpu_sub_xpu_float16
 test_compare_cpu_var_mean_xpu_bfloat16

**Comment by daisyden** [comment]
test_compare_cpu_sub_cuda_float16  also failed on cuda on the sample op arguments. 
tensor([[ 5.8789,  1.1055,  4.2461,  2.1582, -1.9375],
        [-6.7891, -3.7051, -8.3125,  3.7754, -3.4551],
        [ 4.2656, -1.3115,  1.2871, -2.4766, -5.0742],
        [ 4.0859, -3.5020,  2.6934, -3.0977, -0.7280],
        [ 6.6797, -2.5352, -8.8359,  2.1914,  7.1914]], device='cuda:0',
       dtype=torch.float16) (tensor([[ 0.5801, -5.7500, -1.3828,  7.1484, -6.2031],
        [ 7.8203,  3.9648, -0.4629,  3.5273, -4.8359],
        [ 4.7578,  1.9111,  7.6992, -6.6484,  7.2891],
        [ 0.5029, -3.4160, -1.2461,  7.1836, -2.8770],
        [-2.1270, -7.3125,  4.1484, -7.2500, -0.8398]], device='cuda:0',
       dtype=torch.float16),) {'alpha': -3.125}
Verified with pytorch 75ab027fbbe55932ee4be57b3a2e40a9339bd80e.
![image](https://github.com/user-attachments/assets/0ba38a3c-56e5-4300-98ac-dfff08959ec5)

**Comment by daisyden** [comment]
https://github.com/intel/torch-xpu-ops/pull/612 to fix 
 test_compare_cpu_sub_xpu_float16
 test_symnode_hashing
 test_index_ind_dtype_xpu

**Comment by daisyden** [comment]
Closed this issue and keep the rest issue in #614
