### ISSUE TITLE
Performance: Evaluate MaxPool2d forward backward performance gap between IPEX.

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#938]
### 🚀 The feature, motivation and pitch

- Backward: Torch-xpu-ops align with CUDA implementation, using deterministic algorithm.
- Forward: To investigate the gap, after PTI is fixed.

**Comment by huaiyuzh** [comment]
pointnet_bf16_ipex25_1108 is using IPEX max_pool2d, pointnet_bf16_ipex25_1108_stock_pytorch is using stock pytorch max_pool2d.
[pointnet_bf16_ipex25_1108.zip](https://github.com/user-attachments/files/17671866/pointnet_bf16_ipex25_1108.zip)

**Comment by chunhuanMeng** [comment]
The root cause of performance gap  is that ipex have a path to handle some special case which torch-xpu-ops and cuda don't have(ref :https://github.com/intel/intel-extension-for-pytorch/blob/release/xpu/2.5.10/csrc/gpu/aten/operators/DilatedMaxPool2d.cpp#L746),this path will have better parallelism.

**Comment by chunhuanMeng** [comment]
I will fix it in main branch, for `max_out` has not been implemented in the torch-xpu-ops branch that cooperates with ipex 2.5.1. In this way, when running `max_out`, it will fall back to the cpu, which will be slower.

**Comment by chunhuanMeng** [comment]
pr link:https://github.com/intel/torch-xpu-ops/pull/1127
